### ISSUE TITLE
Issue with Nginx proxy manager, page wont load completly.

### ISSUE THREAD

**Issue by Bolex80** [kWeglinski/libretranslate-web#1]
I deployed your front end yesterday and I like it very much as it gives this clean look to LibreTranslate (which I self-host).

But for some reason, if I access the IP directly (no ssl/https), it works perfectly well.

![image](https://github.com/user-attachments/assets/0e192e58-34a8-4040-a4d5-51f9a95926a3)

As soon as I put it behind Nginx reverse proxy manager the page wont load correctly and looses its translation functionality.
![image](https://github.com/user-attachments/assets/08da5d37-55e1-4f49-9a4a-0bcf6d42395e)

It kills me, beacuse I havent actually changed anything and I would really like to be able to run it with SSL on.

Is any one able to check if this is an issue on my side?

I deployed it via portainer using stacks:

version: '3'
services:
  libretranslate:
    image: kweg/pole-libretranslate:latest
    restart: unless-stopped
    environment:
      API: http://192.168.2.5:5000
       # pick one of: 'pole' | 'light' | 'dark' 
      THEME: 'dark'
    ports:
      - 8090:80

**Comment by kWeglinski** [comment]
Hey, sorry I didn't look into github issues thinking nobody cares about this project. Now that I've picked it to add some features I found this GH issue!

Given that it works perfectly fine without reverse proxy -
1. Are you using SSL? (https://translate.~) if so the browser won't allow you to connect to `http://192.168.2.5:5000/` resource as it's not secured
2. If not - I'd guess it's CORS issue. Meaning your API and Client has to be within same main domain. For example if you have translate.somedomain.com then your api would live in apitranslate.somedomain.com (same "somedomain.com") and then the CORS will let it pass, I don't remember what headers does the API send.


I've got it set with SSL and they are translate.domain and apitranslate.domain and it works great.

If the issue persists - share browser console.logs that's you're getting. They should help us tackle the issue together :)

**Comment by tiritibambix** [comment]
Hello! Thank you so much for putting this together. I’ve been eager to use LanguageTool, but I found the lack of a user interface quite challenging.

I’m experiencing a similar issue, though.

Initially, I opted to install all three services using a single docker-compose setup:

```
services:
  libretranslate:
    tty: true
    stdin_open: true
    ports:
      - "5997:5997"
    environment:
      - host=192.168.1.103:5997
    image: libretranslate/libretranslate

  languagetool:
    restart: unless-stopped
    image: elestio/languagetool:latest
    ports:
      - "5998:5998"
    environment:
      - langtool_languageModel=/ngrams
      - Java_Xms=512m
      - Java_Xmx=1g
    volumes:
      - /srv/Files/Languagetools/ngramsDir:/ngrams

  pole-libretranslate:
    restart: unless-stopped
    environment:
      LTAPI: http://192.168.1.103:5997
      API: http://192.168.1.103:5998
      THEME: 'dark'
    ports:
      - "5999:80"
    image: kweg/pole-libretranslate:latest
```

I just want to run it locally or through a VPN tunnel, so I haven't set up any reverse proxy.

When I access the UI, I find that I don’t have the language selection available for LibreTranslate, and I'm also missing options for LanguageTool.

I’m using LibreWolf and Ungoogled Chromium. Here are the console logs for Ungoogled Chromium:

```
index-DjN-QJk0.js:206 
        
        
       GET http://192.168.1.103:5998/languages net::ERR_CONNECTION_REFUSED
getLanguages @ index-DjN-QJk0.js:206
(anonymous) @ index-DjN-QJk0.js:206
(anonymous) @ index-DjN-QJk0.js:206
Ca @ index-DjN-QJk0.js:40
Ho @ index-DjN-QJk0.js:40
gm @ index-DjN-QJk0.js:40
jr @ index-DjN-QJk0.js:38
Sb @ index-DjN-QJk0.js:40
Wr @ index-DjN-QJk0.js:40
n0 @ index-DjN-QJk0.js:40
C @ index-DjN-QJk0.js:25
_ @ index-DjN-QJk0.js:25
index-DjN-QJk0.js:206 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at Object.getLanguages (index-DjN-QJk0.js:206:5013)
    at index-DjN-QJk0.js:206:7951
    at index-DjN-QJk0.js:206:8099
    at Ca (index-DjN-QJk0.js:40:24263)
    at Ho (index-DjN-QJk0.js:40:42318)
    at gm (index-DjN-QJk0.js:40:36565)
    at jr (index-DjN-QJk0.js:38:3274)
    at Sb (index-DjN-QJk0.js:40:41221)
    at Wr (index-DjN-QJk0.js:40:40215)
    at n0 (index-DjN-QJk0.js:40:35675)
getLanguages @ index-DjN-QJk0.js:206
(anonymous) @ index-DjN-QJk0.js:206
(anonymous) @ index-DjN-QJk0.js:206
Ca @ index-DjN-QJk0.js:40
Ho @ index-DjN-QJk0.js:40
gm @ index-DjN-QJk0.js:40
jr @ index-DjN-QJk0.js:38
Sb @ index-DjN-QJk0.js:40
Wr @ index-DjN-QJk0.js:40
n0 @ index-DjN-QJk0.js:40
C @ index-DjN-QJk0.js:25
_ @ index-DjN-QJk0.js:25
index-DjN-QJk0.js:206 
        
        
       GET http://192.168.1.103:5997/v2/languages net::ERR_CONNECTION_REFUSED
getLangs @ index-DjN-QJk0.js:206
(anonymous) @ index-DjN-QJk0.js:206
Ca @ index-DjN-QJk0.js:40
Ho @ index-DjN-QJk0.js:40
Sb @ index-DjN-QJk0.js:40
Wr @ index-DjN-QJk0.js:40
gm @ index-DjN-QJk0.js:40
jr @ index-DjN-QJk0.js:38
(anonymous) @ index-DjN-QJk0.js:40
index-DjN-QJk0.js:206 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at Object.getLangs (index-DjN-QJk0.js:206:10139)
    at index-DjN-QJk0.js:206:12822
    at Ca (index-DjN-QJk0.js:40:24263)
    at Ho (index-DjN-QJk0.js:40:42318)
    at Sb (index-DjN-QJk0.js:40:41166)
    at Wr (index-DjN-QJk0.js:40:40215)
    at gm (index-DjN-QJk0.js:40:36825)
    at jr (index-DjN-QJk0.js:38:3274)
    at index-DjN-QJk0.js:40:34207
```

I’m a bit lost on how to get the ngrams for LanguageTool 🥺

Thanks so much for your assistance!

**Comment by kWeglinski** [comment]
Hey, @tiritibambix thanks for attempting to use my tool :) 

So I have reproduced this when I started the services pointing directly at each other without reverse proxy and this is CORS issue. Sadly we don't have much control over these containers (the problem is at the language tool and libre translate ends) but I'm working on a solution to this. It will also hide and protect the services from outer world which is another benefit. You'll be exposing only this tool.

The easy way around for now this is reverse proxy.

**Comment by kWeglinski** [comment]
@Bolex80 @tiritibambix 
Happy to inform that the issue has been resolved for good. I've added a node.js server that handles all requests for you (therefore no CORS issues). Please make sure to update env variables as names has changed to make more sense. Also make sure to pull latest version ;)

**Comment by tiritibambix** [comment]
That is awesome. I just tried it, and it works as expected. Thank you so much. I'll make you publicity; I'm sure a lot of people need this. :)

The only thing now is that LibreTranslate downloads only some languages, mostly English to other languages. As I'm French, I wish I could translate from my language to another.

Is there any reason for that ? Did I miss something ? Do you want me to open another issue regarding this matter ?

PS: I know French to Engish [exists](https://argos-net.com/v1/translate-fr_en-1_9.argosmodel).
Libretranslate repo refers to `- libretranslate_models:/home/libretranslate/.local:rw` but I'm not sure how to use it here.

**Comment by kWeglinski** [comment]
@tiritibambix thank you very much 😃 

As for libretranslate that's odd. I have exact same docker compose as yours in previous comment (except the host of course) and it downloads all languages. It also downloads them all with every container restart which is a bit annoying.
![image](https://github.com/user-attachments/assets/0523f0fa-9b90-4b1e-982c-221917602ed3)
Works both ways. 

I'd check the docker logs right after container restart to see if there are any download errors and if it attempts to download at all

**Comment by tiritibambix** [comment]
Solution was to put variable
```
      - LT_LOAD_ONLY=en,fr,es
```

If you don't want to them all with every container restart add:
```
    volumes:
      - libretranslate_models:/home/libretranslate/.local:rw

[...]

volumes:
    libretranslate_models:
```

Looks like you can't bond this volume though, which is a shame. Or maybe there's a solution I didn't find in their repo
